platform:
  sepolicy_dirs:
    - device/google/zumapro-sepolicy

includes:
  - common.yml

filters:
  partitions:
    match:
      # TODO: add support for OTA firmware partitions

  dep_files:
    match:
      # Required for building ARM NN HAL
#      - vendor/lib/libOpenCL.so
#      - vendor/lib64/libOpenCL.so
