device:
  name: komodo

platform:
  product_makefile: device/google/caimito/aosp_komodo.mk

includes:
  - snippets/2024.yml

filters:
  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_product.apk
