includes:
  - file-removal.yml
  - overlay-removal.yml
  - removal.yml

device:
  vendor: google_devices
  system_fs_type: ext4
  kernel_repo_url: https://android.googlesource.com/kernel/gs
  has_cellular: true

  build_id: AP4A.250205.002

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/
