filters:
  partitions:
    match:
      # Partitions we do not want
      - vbmeta_system
      - vbmeta_vendor

  props:
    match:
      # Debug
      - ro.adb.secure
      # intentionally removed, see device/google/zuma commit
#      - ro.arm64.memtag.bootctl_supported
#      - persist.sys.sf.native_mode
#      - persist.vendor.usb.displayport.enabled
    prefix:
      # these props disable memory tagging for some of system processes
#      - persist.arm64.memtag.app.
#      - persist.arm64.memtag.system_server
      # APEX
      - ro.apex.updatable
      # Debug
      - log.tag.
      # Default alarm
#      - ro.config.alarm_alert
      # Google Assistant
      - ro.opa.eligible_device
#      - ro.hotword.detection_service_required
      # Google IME
      - ro.com.google.ime
      # SetupWizard
#      - ro.setupwizard.
#      - setupwizard.
      # Storage manager
      - ro.storage_manager.
      # Theme
      - ro.boot.vendor.overlay.theme
      # aware is not part of AOSP
      - ro.vendor.aware_available
      # disable llkd
      - ro.llkd.enable
      # irrelevant build region
#      - ro.vendor.config.build_carrier
      # irrelevant keyguard prop
      - keyguard.no_require_sim
      # mobile data
      - ro.com.android.prov_mobiledata
      # privapps
      - ro.control_privapp_permissions
      # unused carrier setup page
#      - ro.carriersetup.vzw_consent_page
      # unused gms props
      - ro.atrace.core.services
      - ro.com.google.clientidbase
      - ro.error.receiver.system.apps
      # unused ssrestart debug prop
#      - vendor.debug.ssrdump.type
      # we dont ship system_other
#      - ro.cp_system_other_odex
      # we dont want this debug trash on sf
      - debug.sf.enable_egl_image_tracker

  sepolicy_dirs:
    prefix:
      - device/google/gs-common/gcam_app/
    match:
      - hardware/google/pixel-sepolicy/googlebattery
      - hardware/google/pixel-sepolicy/flipendo
      - hardware/google/pixel-sepolicy/ramdump
      - hardware/google/pixel-sepolicy/sota_app/system_ext
      - hardware/google/pixel-sepolicy/turbo_adapter
